apiVersion: v1
kind: ConfigMap
metadata:
  name: tornado-config
  namespace: tornado
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  DataProtection__KeysPath: "/var/tornado-keys"
  SelfBaseUrl: "http://tornado.tornado.svc.cluster.local"
