apiVersion: v1
kind: ConfigMap
metadata:
  name: tornado-config
  namespace: tornado
data:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  SelfBaseUrl: "http://tornado.tornado.svc.cluster.local"
