apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tornado
  namespace: tornado
spec:
  ingressClassName: nginx
  rules:
    - host: tornado.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tornado
                port:
                  number: 80
