apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tornado
  namespace: tornado
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: "tornado_affinity"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: traefik
  rules:
    - host: tornado.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tornado
                port:
                  number: 80
