apiVersion: v1
kind: Service
metadata:
  name: tornado
  namespace: tornado
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  selector:
    app: tornado
  ports:
    - name: http
      port: 80
      targetPort: 8080
